// <auto-generated />
using System;
using EDP;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDP.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221218180916_Create1")]
    partial class Create1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EDP.Models.Cart", b =>
                {
                    b.Property<string>("cart_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cart_id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EDP.Models.Claimed_Voucher", b =>
                {
                    b.Property<string>("claimed_voucher_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voucher_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voucher_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("claimed_voucher_id");

                    b.ToTable("ClaimedVouchers");
                });

            modelBuilder.Entity("EDP.Models.Purchase_History", b =>
                {
                    b.Property<string>("purchase_history_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("discounted_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("payment_reference_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("percentage_off")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("purchase_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("voucher_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("purchase_history_id");

                    b.ToTable("PurchaseHistories");
                });

            modelBuilder.Entity("EDP.Models.Purchased_Item", b =>
                {
                    b.Property<string>("purchased_item_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("purchase_history_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("purchased_item_id");

                    b.ToTable("PurchasedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
